### ISSUE TITLE
Make sure the platform specifier works throughout

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/juliaup#32]
The new platform separator is now `~`, so one would say things like `juliaup add 1.6.1~x86`. This almost certainly is not implemented throughout yet.

**Comment by Vaibhavdixit02** [comment]
This 

```
~ juliaup add 1.6.1~x86
Checking for new Julia versions
Error: '1.6.1~x86' is not a valid Julia version or channel name.
```

doesn't seem to work, other than `x64` the other two don't show up in the `list` or work, is that expected?

**Comment by davidanthoff** [comment]
What OS/Platform are you on? For example on Mac, that build just doesn't exist.

**Comment by Vaibhavdixit02** [comment]
Yeah I am on Mac, I got it from https://julialang.org/downloads/#current_stable_release (the Apple silicon option there). I may be misunderstanding where it should exist?

**Comment by davidanthoff** [comment]
There are no Julia x86 builds for Apple in general, Julia only supports aarch64 and x64 on Mac.

**Comment by Vaibhavdixit02** [comment]
Ah sorry that was incorrect, this came up for me because I needed aarch64 and was using x86 as an example from the readme for adding architecture-specific version.

To clarify, the only options with `juliaup list` (for any julia version) on Mac are 

```
 1.11.1             1.11.1+0.x64.apple.darwin14        
 1.11.1~x64         1.11.1+0.x64.apple.darwin14
```

and the aarch64 is missing, and hence the command to add it doesn't work and both of these give x86_64

**Comment by davidanthoff** [comment]
That means you have installed the x64 version of Juliaup, not the aarch64 version. If you installed Julia/Juliaup with
```
curl -fsSL https://install.julialang.org | sh
```
it should automatically have installed the aarch64 version for you if that is your OS...

**Comment by davidanthoff** [comment]
You might have installed Juliaup before we had a aarch64 version :)
