### ISSUE TITLE
Updated Store app won't launch

### ISSUE THREAD

**Issue by BioTurboNick** [davidanthoff/juliaup#36]
Something broke. I had the first release from the store that you posted on Slack, then just updated it with your new post, and now it won't launch. A console window very briefly flashes up then disappears.

I had the previous one running while updating.

**Comment by BioTurboNick** [comment]
That last part may not have to do with anything. I cleared it as best I could and reinstalled fresh. Still won't launch.

Windows 10 64-bit Version 21H1 (OS Build 19043.985)

Is there a log I can send you, or do you get telemetry from Microsoft?

**Comment by davidanthoff** [comment]
Could you check what version of the app you have installed? You can see that in the Windows Store app, and it should be 1.0.14.0.

Next thing would be to delete the entire folder `~/.julia/juliaup` and then try again.

Also, from a command prompt, can you try to start both `julia` and `juliaup`. Do both not start, or is the problem with just one of them?

**Comment by davidanthoff** [comment]
Actually, I have a theory: I might have declared a wrong dependency on the VC runtime. If you _can_ start `juliaup` but not `julia`, then that might explain it. I'm also preparing a new release that might fix this.

**Comment by davidanthoff** [comment]
Alright, I published version 1.0.16.0 to the app store that fixes a problem that I distributed the wrong C++ runtime libs. I think that could well explain what you are seeing. Could you try again after you update in the store to 1.0.16.0?

**Comment by BioTurboNick** [comment]
I deleted all files in juliaup, then from the command prompt, then ran `julia`.

```
No Julia version for channel 1 is installed on this system. Run:

  juliaup update

to install Julia 1, the latest Julia version for the current channel.
```

For the first problem: Windows console windows are closed as soon as their program exits. I suggest adding a "press any key to exit" read prompt to ensure the window stays open so the message can be read.

**Comment by davidanthoff** [comment]
Alright, closing this issue because it seems that the new update has fixed things to the point that things run, now we just need to fix the user experience for that, tracked in a new issue.
